name: Lint Markdown

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - *

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Markdown
        uses: actionshub/markdownlint@main
